### ISSUE TITLE
Vacation application modification history

### ISSUE THREAD

**Issue by mishavetl** [ASbeletsky/TimeOffTracker#80]
## Overview

The current implementation does not support the viewing of modifications made to a vacation application.

## Requirements

 * All versions of vacation details should be stored. It includes:
   - Assigned managers,
   - Status changes,
   - From date,
   - To date,
   - Vacation type changes,
   - etc.
 * Apart from vacation details the following information should be stored:
   - The identity of a user, who changed vacation details (only admins should be allowed),
   - When the modification occurred.

Estimate: 15 hours
Deadline: 29.02.2020

**Comment by vitderkach** [comment]
### **Implementation guidelines**

1. Explore the design of already exciting database;
2. Design a table, which will store all needed information;
2.1. As a solution, consider an exicting possibility of implementing temporal table in SQL Server: https://www.eidias.com/blog/2018/8/29/using-sql-temporal-tables-with-entity-framework-core, https://www.nuget.org/packages/EntityFrameworkCore.TemporalTables, https://docs.microsoft.com/en-us/archive/msdn-magazine/2017/march/cutting-edge-soft-updates-with-temporal-tables;
2.2. Otherwise, implement an own design of temporal table;
3. Add all needed code to the project and changes to the database using migration.
